name: CI

on:
  push:
    branches: [ master, ci-attempt ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-16-dev libclang-16-dev libclang-cpp16-dev gcc-14 g++-14
        
    - name: Set GCC 14 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: .github/etc/requirements.txt

    - name: Install Python dependencies
      shell: bash
      run: pip install -r .github/etc/requirements.txt

    - name: Conan cache
      uses: actions/cache@v4
      with:
        path: conan_cache_save.tgz
        key: conan-${{ github.runner_name }}-${{ hashFiles('conan*.[pl][yo]*') }}

    - name: Setup Conan and install dependencies
      shell: bash
      run: bash .github/scripts/conan-ci-setup.sh
        
    - name: Configure build
      run: cmake --preset=conan-dev
      
    - name: Build
      run: cmake --build --preset=conan-dev
      
    - name: Run tests
      run: ctest --preset=default